### ISSUE TITLE
cappsule.ko: Unknown error 269 on Ubuntu 16.04

### ISSUE THREAD

**Issue by Kaedo** [cappsule/cappsule-hypervisor#2]
Hello Quarkslab,
I tried to install cappsule on a fresh osboxes.org virtualbox image of Ubuntu 16.04.
I followed your instruction in the documentation and build the deb package myself. I tried your prebuild deb package, but it did not work either.

I used the build command as suggested by you:

**osboxes@osboxes:~$** `./tools/build_package.py -f ./cappsule.deb`
**osboxes@osboxes:~$** `sudo dpkg --force-confnew -i ../cappsule.deb`

In order to load the cappsule.ko i first created _/lib/modprobe.d/cappsule.conf_ and edit it as following:
`install cappsule insmod /usr/local/cappsule/usr/share/cappsule/cappsule.ko`

**osboxes@osboxes$** `sudo modprobe cappsule`
insmod: ERROR: could not insert module /usr/local/cappsule/usr/share/cappsule/cappsule.ko: Unknown error 269

**osboxes@osboxes:~$** `lsmod | grep capps`
cappsule_guest         28672  0

**osboxes@osboxes:~$** `dmesg | grep capps`
[    5.119707] cappsule_guest: module verification failed: signature and/or required key missing - tainting kernel

I tried to launch the daemon anyway, just to ensure I did not missed anything:

**osboxes@osboxes:~$** `sudo /usr/local/cappsule/usr/bin/daemon --debug`
daemon fe66cf6
daemon: finit_module: File exists

**osboxes@osboxes:~$** `/usr/local/cappsule/usr/bin/virt exec firefox`
Client error: cannot connect to cappsule server.

I use the following kernel
**osboxes@osboxes$** `uname -a`
Linux osboxes 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

If you need additional information, just let me know.

Kind Regards
Kaedo

**Comment by cappsule** [comment]
I don't know why you get an error number instead of an explicit error message. Anyway, the [error](https://github.com/cappsule/cappsule-hypervisor/blob/master/include/cuapi/error.h#L38) [seems](https://github.com/cappsule/cappsule-hypervisor/blob/master/trusted/cappsule.c#L98) that Intel VT-x isn't enabled. Could you confirm that enabling VirtualBox option `Enable VT-x/AMD-V and Enable Nested Paging` fixes this issue?

**Comment by Kaedo** [comment]
I looked it up, VT-x/AMD-V are enabled in Virtualbox and my host CPU have it also checked via:

`cat /proc/cpuinfo| egrep --color "vmx|svm"`

I will cross check it, with the vm of a colleague, which had it already running.

**Comment by Kaedo** [comment]
So now I have test results of the Cappsule VM on OSX, Windows, Ubuntu und Gentoo Linux.

On each of them I get the same error as above (Unknown error 269)

On which Virtualbox version did you test Cappsule? Maybe thats the source of error.
In addition, how did you load the hypervisor module?

**Comment by cappsule** [comment]
Sorry, I should have read your first comment more carefully. The kernel modules aren't meant to be loaded manually: cappsule must be launched thanks to the `daemon` command. The [documentation](https://github.com/cappsule/cappsule-doc/blob/master/usage.rst) should be clearer on that point.

**Comment by Kaedo** [comment]
Ok, thx for solving the startup problem.

But still it is not possible to launch an application via:

**osboxes@osboxes:~$** `/usr/local/cappsule/usr/bin/virt exec firefox`
Client error: cannot connect to cappsule server.

Do you know which issue could cause this problem?

**Comment by cappsule** [comment]
Are you sure that `daemon` is running?

**Comment by Kaedo** [comment]
I used the command below for starting it:

**osboxes@osboxes:~$** `sudo /usr/local/cappsule/usr/bin/daemon --debug`
daemon fe66cf6
daemon: finit_module: File exists

**Comment by cappsule** [comment]
`daemon` isn't running then and it fails to run because `cappsule` (and/or `cappsule_guest`) kernel modules are still loaded.

You first comment mentioned that you modified `/lib/modprobe.d/cappsule.conf`. Could you restore this file to its original verson and reboot your VM please?

**Comment by Kaedo** [comment]
The file /lib/modprobe.d/cappsule.conf did not exist, until I have created it.

But I will delete it, restart the VM and take a look, if it then works.

**Comment by Kaedo** [comment]
It did not work, I got the same results:

**osboxes@osboxes:~$** `sudo /usr/local/cappsule/usr/bin/daemon --debug`
daemon fe66cf6
daemon: finit_module: File exists

**osboxes@osboxes:~$** `/usr/local/cappsule/usr/bin/virt exec firefox`
Client error: cannot connect to cappsule server.

**Comment by cappsule** [comment]
The first error message is quite explicit: one of cappsule's kernel module is still loaded.

Since you installed cappsule with the Ubuntu package, `daemon` automatically starts during the boot thanks to a systemd configuration file (`/lib/systemd/system/cappsule.service`) . You shouldn't need to start `daemon` manually and `virt` should also be ready to use. Could you check that there's no error in `/var/log/cappsule/*.log`?

**Comment by Kaedo** [comment]
Ok, I got the following information:


**root@osboxes:/usr/local/cappsule/usr/bin#** cat /var/log/cappsule/daemon.log 
```
daemon fe66cf6
daemon: can't launch hypervisor: CPU doesn't support VMX
```

Which is stranged, but I googled around and found out, that VBox does not support [nested Virtual Machines](https://www.virtualbox.org/ticket/4032).

Is this correct or did I miss something?

**Comment by cappsule** [comment]
Well, I'm afraid you're right... VirtualBox doesn't support nested virtualization. I misunderstood VirtualBox option "Enable VT-x/AMD-V and Enable Nested Paging" and blindly assumed that the conversion from `.vmdk` to `.ovf` would work directly. Unfortunately, I think that you need to use VMware.

I updated the documentation accordingly. Thanks a lot for your bug report!
